export const demoTrackData: SpotifyApi.TrackObjectFull[] = [
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/6M2wZ9GZgrQXHCFfjv46we',
          },
          href: 'https://api.spotify.com/v1/artists/6M2wZ9GZgrQXHCFfjv46we',
          id: '6M2wZ9GZgrQXHCFfjv46we',
          name: 'Dua Lipa',
          type: 'artist',
          uri: 'spotify:artist:6M2wZ9GZgrQXHCFfjv46we',
        },
      ],
      available_markets: [
        'AR',
        'AU',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
        'JP',
        'TH',
        'VN',
        'RO',
        'IL',
        'ZA',
        'SA',
        'AE',
        'BH',
        'QA',
        'OM',
        'KW',
        'EG',
        'MA',
        'DZ',
        'TN',
        'LB',
        'JO',
        'PS',
        'IN',
        'BY',
        'KZ',
        'MD',
        'UA',
        'AL',
        'BA',
        'HR',
        'ME',
        'MK',
        'RS',
        'SI',
        'KR',
        'BD',
        'PK',
        'LK',
        'GH',
        'KE',
        'NG',
        'TZ',
        'UG',
        'AG',
        'AM',
        'BS',
        'BB',
        'BZ',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/5lKlFlReHOLShQKyRv6AL9',
      },
      href: 'https://api.spotify.com/v1/albums/5lKlFlReHOLShQKyRv6AL9',
      id: '5lKlFlReHOLShQKyRv6AL9',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273a34d440eb5a9b188c066e09a',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02a34d440eb5a9b188c066e09a',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851a34d440eb5a9b188c066e09a',
          width: 64,
        },
      ],
      name: 'Future Nostalgia',
      release_date: '2020-03-27',
      release_date_precision: 'day',
      total_tracks: 13,
      type: 'album',
      uri: 'spotify:album:5lKlFlReHOLShQKyRv6AL9',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/6M2wZ9GZgrQXHCFfjv46we',
        },
        href: 'https://api.spotify.com/v1/artists/6M2wZ9GZgrQXHCFfjv46we',
        id: '6M2wZ9GZgrQXHCFfjv46we',
        name: 'Dua Lipa',
        type: 'artist',
        uri: 'spotify:artist:6M2wZ9GZgrQXHCFfjv46we',
      },
    ],
    available_markets: [
      'AR',
      'AU',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
      'JP',
      'TH',
      'VN',
      'RO',
      'IL',
      'ZA',
      'SA',
      'AE',
      'BH',
      'QA',
      'OM',
      'KW',
      'EG',
      'MA',
      'DZ',
      'TN',
      'LB',
      'JO',
      'PS',
      'IN',
      'BY',
      'KZ',
      'MD',
      'UA',
      'AL',
      'BA',
      'HR',
      'ME',
      'MK',
      'RS',
      'SI',
      'KR',
      'BD',
      'PK',
      'LK',
      'GH',
      'KE',
      'NG',
      'TZ',
      'UG',
      'AG',
      'AM',
      'BS',
      'BB',
      'BZ',
    ],
    disc_number: 1,
    duration_ms: 203808,
    explicit: false,
    external_ids: { isrc: 'GBAHT1901299' },
    external_urls: {
      spotify: 'https://open.spotify.com/track/1dI77VhaLcQSgQLSnIs03D',
    },
    href: 'https://api.spotify.com/v1/tracks/1dI77VhaLcQSgQLSnIs03D',
    id: '1dI77VhaLcQSgQLSnIs03D',
    is_local: false,
    name: 'Levitating',
    popularity: 58,
    preview_url:
      'https://p.scdn.co/mp3-preview/ac28d1b0be285ed3bfd8e9fa5fad133776d7cf36?cid=ce28908d95b34872a301a62ca8c95194',
    track_number: 5,
    type: 'audio_features',
    uri: 'spotify:track:1dI77VhaLcQSgQLSnIs03D',
    danceability: 0.695,
    energy: 0.884,
    key: 6,
    loudness: -2.278,
    mode: 0,
    speechiness: 0.0753,
    acousticness: 0.0561,
    instrumentalness: 0,
    liveness: 0.213,
    valence: 0.914,
    tempo: 103.014,
    track_href: 'https://api.spotify.com/v1/tracks/1dI77VhaLcQSgQLSnIs03D',
    analysis_url:
      'https://api.spotify.com/v1/audio-analysis/1dI77VhaLcQSgQLSnIs03D',
    time_signature: 4,
  },
  {
    album: {
      album_type: 'single',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/2tIP7SsRs7vjIcLrU85W8J',
          },
          href: 'https://api.spotify.com/v1/artists/2tIP7SsRs7vjIcLrU85W8J',
          id: '2tIP7SsRs7vjIcLrU85W8J',
          name: 'The Kid LAROI',
          type: 'artist',
          uri: 'spotify:artist:2tIP7SsRs7vjIcLrU85W8J',
        },
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/1uNFoZAHBGtllmzznpCI3s',
          },
          href: 'https://api.spotify.com/v1/artists/1uNFoZAHBGtllmzznpCI3s',
          id: '1uNFoZAHBGtllmzznpCI3s',
          name: 'Justin Bieber',
          type: 'artist',
          uri: 'spotify:artist:1uNFoZAHBGtllmzznpCI3s',
        },
      ],
      available_markets: [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
        'JP',
        'TH',
        'VN',
        'RO',
        'IL',
        'ZA',
        'SA',
        'AE',
        'BH',
        'QA',
        'OM',
        'KW',
        'EG',
        'MA',
        'DZ',
        'TN',
        'LB',
        'JO',
        'PS',
        'IN',
        'BY',
        'KZ',
        'MD',
        'UA',
        'AL',
        'BA',
        'HR',
        'ME',
        'MK',
        'RS',
        'SI',
        'KR',
        'BD',
        'PK',
        'LK',
        'GH',
        'KE',
        'NG',
        'TZ',
        'UG',
        'AG',
        'AM',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/4QLAtpLNUsHEYrcHXmMIZZ',
      },
      href: 'https://api.spotify.com/v1/albums/4QLAtpLNUsHEYrcHXmMIZZ',
      id: '4QLAtpLNUsHEYrcHXmMIZZ',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b27341e31d6ea1d493dd77933ee5',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e0241e31d6ea1d493dd77933ee5',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d0000485141e31d6ea1d493dd77933ee5',
          width: 64,
        },
      ],
      name: 'STAY (with Justin Bieber)',
      release_date: '2021-07-09',
      release_date_precision: 'day',
      total_tracks: 1,
      type: 'album',
      uri: 'spotify:album:4QLAtpLNUsHEYrcHXmMIZZ',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/2tIP7SsRs7vjIcLrU85W8J',
        },
        href: 'https://api.spotify.com/v1/artists/2tIP7SsRs7vjIcLrU85W8J',
        id: '2tIP7SsRs7vjIcLrU85W8J',
        name: 'The Kid LAROI',
        type: 'artist',
        uri: 'spotify:artist:2tIP7SsRs7vjIcLrU85W8J',
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/1uNFoZAHBGtllmzznpCI3s',
        },
        href: 'https://api.spotify.com/v1/artists/1uNFoZAHBGtllmzznpCI3s',
        id: '1uNFoZAHBGtllmzznpCI3s',
        name: 'Justin Bieber',
        type: 'artist',
        uri: 'spotify:artist:1uNFoZAHBGtllmzznpCI3s',
      },
    ],
    available_markets: [
      'AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
      'JP',
      'TH',
      'VN',
      'RO',
      'IL',
      'ZA',
      'SA',
      'AE',
      'BH',
      'QA',
      'OM',
      'KW',
      'EG',
      'MA',
      'DZ',
      'TN',
      'LB',
      'JO',
      'PS',
      'IN',
      'BY',
      'KZ',
      'MD',
      'UA',
      'AL',
      'BA',
      'HR',
      'ME',
      'MK',
      'RS',
      'SI',
      'KR',
      'BD',
      'PK',
      'LK',
      'GH',
      'KE',
      'NG',
      'TZ',
      'UG',
      'AG',
      'AM',
    ],
    disc_number: 1,
    duration_ms: 141806,
    explicit: true,
    external_ids: { isrc: 'USSM12103949' },
    external_urls: {
      spotify: 'https://open.spotify.com/track/5HCyWlXZPP0y6Gqq8TgA20',
    },
    href: 'https://api.spotify.com/v1/tracks/5HCyWlXZPP0y6Gqq8TgA20',
    id: '5HCyWlXZPP0y6Gqq8TgA20',
    is_local: false,
    name: 'STAY (with Justin Bieber)',
    popularity: 86,
    preview_url:
      'https://p.scdn.co/mp3-preview/718a2eb032524494a01f73d80af2bcf176c9f3e2?cid=ce28908d95b34872a301a62ca8c95194',
    track_number: 1,
    type: 'audio_features',
    uri: 'spotify:track:5HCyWlXZPP0y6Gqq8TgA20',
    danceability: 0.591,
    energy: 0.764,
    key: 1,
    loudness: -5.484,
    mode: 1,
    speechiness: 0.0483,
    acousticness: 0.0383,
    instrumentalness: 0,
    liveness: 0.103,
    valence: 0.478,
    tempo: 169.928,
    track_href: 'https://api.spotify.com/v1/tracks/5HCyWlXZPP0y6Gqq8TgA20',
    analysis_url:
      'https://api.spotify.com/v1/audio-analysis/5HCyWlXZPP0y6Gqq8TgA20',
    time_signature: 4,
  },
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/1McMsnEElThX1knmY4oliG',
          },
          href: 'https://api.spotify.com/v1/artists/1McMsnEElThX1knmY4oliG',
          id: '1McMsnEElThX1knmY4oliG',
          name: 'Olivia Rodrigo',
          type: 'artist',
          uri: 'spotify:artist:1McMsnEElThX1knmY4oliG',
        },
      ],
      available_markets: [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'SE',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
        'JP',
        'TH',
        'VN',
        'RO',
        'IL',
        'ZA',
        'SA',
        'AE',
        'BH',
        'QA',
        'OM',
        'KW',
        'EG',
        'MA',
        'DZ',
        'TN',
        'LB',
        'JO',
        'PS',
        'IN',
        'BY',
        'KZ',
        'MD',
        'UA',
        'AL',
        'BA',
        'HR',
        'ME',
        'MK',
        'RS',
        'SI',
        'KR',
        'BD',
        'PK',
        'LK',
        'GH',
        'KE',
        'NG',
        'TZ',
        'UG',
        'AG',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/6s84u2TUpR3wdUv4NgKA2j',
      },
      href: 'https://api.spotify.com/v1/albums/6s84u2TUpR3wdUv4NgKA2j',
      id: '6s84u2TUpR3wdUv4NgKA2j',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273a91c10fe9472d9bd89802e5a',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02a91c10fe9472d9bd89802e5a',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851a91c10fe9472d9bd89802e5a',
          width: 64,
        },
      ],
      name: 'SOUR',
      release_date: '2021-05-21',
      release_date_precision: 'day',
      total_tracks: 11,
      type: 'album',
      uri: 'spotify:album:6s84u2TUpR3wdUv4NgKA2j',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/1McMsnEElThX1knmY4oliG',
        },
        href: 'https://api.spotify.com/v1/artists/1McMsnEElThX1knmY4oliG',
        id: '1McMsnEElThX1knmY4oliG',
        name: 'Olivia Rodrigo',
        type: 'artist',
        uri: 'spotify:artist:1McMsnEElThX1knmY4oliG',
      },
    ],
    available_markets: [
      'AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
      'JP',
      'TH',
      'VN',
      'RO',
      'IL',
      'ZA',
      'SA',
      'AE',
      'BH',
      'QA',
      'OM',
      'KW',
      'EG',
      'MA',
      'DZ',
      'TN',
      'LB',
      'JO',
      'PS',
      'IN',
      'BY',
      'KZ',
      'MD',
      'UA',
      'AL',
      'BA',
      'HR',
      'ME',
      'MK',
      'RS',
      'SI',
      'KR',
      'BD',
      'PK',
      'LK',
      'GH',
      'KE',
      'NG',
      'TZ',
      'UG',
      'AG',
    ],
    disc_number: 1,
    duration_ms: 178147,
    explicit: true,
    external_ids: { isrc: 'USUG12101245' },
    external_urls: {
      spotify: 'https://open.spotify.com/track/4ZtFanR9U6ndgddUvNcjcG',
    },
    href: 'https://api.spotify.com/v1/tracks/4ZtFanR9U6ndgddUvNcjcG',
    id: '4ZtFanR9U6ndgddUvNcjcG',
    is_local: false,
    name: 'good 4 u',
    popularity: 87,
    preview_url:
      'https://p.scdn.co/mp3-preview/b842388e0a8bb4c8667f77d645b25fdcd50961c1?cid=ce28908d95b34872a301a62ca8c95194',
    track_number: 6,
    type: 'audio_features',
    uri: 'spotify:track:4ZtFanR9U6ndgddUvNcjcG',
    danceability: 0.563,
    energy: 0.664,
    key: 9,
    loudness: -5.044,
    mode: 1,
    speechiness: 0.154,
    acousticness: 0.335,
    instrumentalness: 0,
    liveness: 0.0849,
    valence: 0.688,
    tempo: 166.928,
    track_href: 'https://api.spotify.com/v1/tracks/4ZtFanR9U6ndgddUvNcjcG',
    analysis_url:
      'https://api.spotify.com/v1/audio-analysis/4ZtFanR9U6ndgddUvNcjcG',
    time_signature: 4,
  },
  {
    album: {
      album_type: 'single',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq',
          },
          href: 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
          id: '7jVv8c5Fj3E9VhNjxT4snq',
          name: 'Lil Nas X',
          type: 'artist',
          uri: 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq',
        },
      ],
      available_markets: [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'SE',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
        'JP',
        'TH',
        'VN',
        'RO',
        'IL',
        'ZA',
        'SA',
        'AE',
        'BH',
        'QA',
        'OM',
        'KW',
        'EG',
        'MA',
        'DZ',
        'TN',
        'LB',
        'JO',
        'PS',
        'IN',
        'BY',
        'KZ',
        'MD',
        'UA',
        'AL',
        'BA',
        'HR',
        'ME',
        'MK',
        'RS',
        'SI',
        'KR',
        'BD',
        'PK',
        'LK',
        'GH',
        'KE',
        'NG',
        'TZ',
        'UG',
        'AG',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/2Hjcfw8zHN4dJDZJGOzLd6',
      },
      href: 'https://api.spotify.com/v1/albums/2Hjcfw8zHN4dJDZJGOzLd6',
      id: '2Hjcfw8zHN4dJDZJGOzLd6',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273664034dd80e91b28f773598d',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02664034dd80e91b28f773598d',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851664034dd80e91b28f773598d',
          width: 64,
        },
      ],
      name: 'MONTERO (Call Me By Your Name)',
      release_date: '2021-03-31',
      release_date_precision: 'day',
      total_tracks: 3,
      type: 'album',
      uri: 'spotify:album:2Hjcfw8zHN4dJDZJGOzLd6',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq',
        },
        href: 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
        id: '7jVv8c5Fj3E9VhNjxT4snq',
        name: 'Lil Nas X',
        type: 'artist',
        uri: 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq',
      },
    ],
    available_markets: [
      'AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
      'JP',
      'TH',
      'VN',
      'RO',
      'IL',
      'ZA',
      'SA',
      'AE',
      'BH',
      'QA',
      'OM',
      'KW',
      'EG',
      'MA',
      'DZ',
      'TN',
      'LB',
      'JO',
      'PS',
      'IN',
      'BY',
      'KZ',
      'MD',
      'UA',
      'AL',
      'BA',
      'HR',
      'ME',
      'MK',
      'RS',
      'SI',
      'KR',
      'BD',
      'PK',
      'LK',
      'GH',
      'KE',
      'NG',
      'TZ',
      'UG',
      'AG',
    ],
    disc_number: 1,
    duration_ms: 137876,
    explicit: true,
    external_ids: { isrc: 'USSM12100531' },
    external_urls: {
      spotify: 'https://open.spotify.com/track/67BtfxlNbhBmCDR2L2l8qd',
    },
    href: 'https://api.spotify.com/v1/tracks/67BtfxlNbhBmCDR2L2l8qd',
    id: '67BtfxlNbhBmCDR2L2l8qd',
    is_local: false,
    name: 'MONTERO (Call Me By Your Name)',
    popularity: 76,
    preview_url:
      'https://p.scdn.co/mp3-preview/f653a289186d0de9a7685e2958ed5d86e073f3c0?cid=ce28908d95b34872a301a62ca8c95194',
    track_number: 1,
    type: 'audio_features',
    uri: 'spotify:track:67BtfxlNbhBmCDR2L2l8qd',
    danceability: 0.61,
    energy: 0.508,
    key: 8,
    loudness: -6.682,
    mode: 0,
    speechiness: 0.152,
    acousticness: 0.297,
    instrumentalness: 0,
    liveness: 0.384,
    valence: 0.758,
    tempo: 178.818,
    track_href: 'https://api.spotify.com/v1/tracks/67BtfxlNbhBmCDR2L2l8qd',
    analysis_url:
      'https://api.spotify.com/v1/audio-analysis/67BtfxlNbhBmCDR2L2l8qd',
    time_signature: 4,
  },
  {
    album: {
      album_type: 'single',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/3Nrfpe0tUJi4K4DXYWgMUX',
          },
          href: 'https://api.spotify.com/v1/artists/3Nrfpe0tUJi4K4DXYWgMUX',
          id: '3Nrfpe0tUJi4K4DXYWgMUX',
          name: 'BTS',
          type: 'artist',
          uri: 'spotify:artist:3Nrfpe0tUJi4K4DXYWgMUX',
        },
      ],
      available_markets: [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'SE',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
        'JP',
        'TH',
        'VN',
        'RO',
        'IL',
        'ZA',
        'SA',
        'AE',
        'BH',
        'QA',
        'OM',
        'KW',
        'EG',
        'MA',
        'DZ',
        'TN',
        'LB',
        'JO',
        'PS',
        'IN',
        'BY',
        'KZ',
        'MD',
        'UA',
        'AL',
        'BA',
        'HR',
        'ME',
        'MK',
        'RS',
        'SI',
        'KR',
        'BD',
        'PK',
        'LK',
        'GH',
        'KE',
        'NG',
        'TZ',
        'UG',
        'AG',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/0PBQ3Cp6NG8WX0G9KQVNMP',
      },
      href: 'https://api.spotify.com/v1/albums/0PBQ3Cp6NG8WX0G9KQVNMP',
      id: '0PBQ3Cp6NG8WX0G9KQVNMP',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273240447f2da1433d8f4303596',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02240447f2da1433d8f4303596',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851240447f2da1433d8f4303596',
          width: 64,
        },
      ],
      name: 'Butter (Hotter, Sweeter, Cooler)',
      release_date: '2021-06-04',
      release_date_precision: 'day',
      total_tracks: 5,
      type: 'album',
      uri: 'spotify:album:0PBQ3Cp6NG8WX0G9KQVNMP',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/3Nrfpe0tUJi4K4DXYWgMUX',
        },
        href: 'https://api.spotify.com/v1/artists/3Nrfpe0tUJi4K4DXYWgMUX',
        id: '3Nrfpe0tUJi4K4DXYWgMUX',
        name: 'BTS',
        type: 'artist',
        uri: 'spotify:artist:3Nrfpe0tUJi4K4DXYWgMUX',
      },
    ],
    available_markets: [
      'AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
      'JP',
      'TH',
      'VN',
      'RO',
      'IL',
      'ZA',
      'SA',
      'AE',
      'BH',
      'QA',
      'OM',
      'KW',
      'EG',
      'MA',
      'DZ',
      'TN',
      'LB',
      'JO',
      'PS',
      'IN',
      'BY',
      'KZ',
      'MD',
      'UA',
      'AL',
      'BA',
      'HR',
      'ME',
      'MK',
      'RS',
      'SI',
      'KR',
      'BD',
      'PK',
      'LK',
      'GH',
      'KE',
      'NG',
      'TZ',
      'UG',
      'AG',
    ],
    disc_number: 1,
    duration_ms: 164442,
    explicit: false,
    external_ids: { isrc: 'QM6MZ2156864' },
    external_urls: {
      spotify: 'https://open.spotify.com/track/1mWdTewIgB3gtBM3TOSFhB',
    },
    href: 'https://api.spotify.com/v1/tracks/1mWdTewIgB3gtBM3TOSFhB',
    id: '1mWdTewIgB3gtBM3TOSFhB',
    is_local: false,
    name: 'Butter',
    popularity: 73,
    preview_url:
      'https://p.scdn.co/mp3-preview/4d63fe1638aa41592706f835bd076443b09d8afa?cid=ce28908d95b34872a301a62ca8c95194',
    track_number: 1,
    type: 'audio_features',
    uri: 'spotify:track:1mWdTewIgB3gtBM3TOSFhB',
    danceability: 0.759,
    energy: 0.459,
    key: 8,
    loudness: -5.187,
    mode: 1,
    speechiness: 0.0948,
    acousticness: 0.00323,
    instrumentalness: 0,
    liveness: 0.0906,
    valence: 0.695,
    tempo: 109.997,
    track_href: 'https://api.spotify.com/v1/tracks/1mWdTewIgB3gtBM3TOSFhB',
    analysis_url:
      'https://api.spotify.com/v1/audio-analysis/1mWdTewIgB3gtBM3TOSFhB',
    time_signature: 4,
  },
];
