export const demoSongData = [
  { name: 'Levitating', artists: 'Dua Lipa', album: 'Future Nostalgia' },
  { name: 'Stay', artists: 'The Kid LAROI, Justin Bieber', album: 'Stay' },
  { name: 'Good 4 U', artists: 'Olivia Rodrigo', album: 'SOUR' },
  {
    name: 'Montero (Call Me By Your Name)',
    artists: 'Lil Nas X',
    album: 'Montero',
  },
  { name: 'Butter', artists: 'BTS', album: 'Butter' },
  {
    name: 'Peaches',
    artists: 'Justin Bieber, Daniel Caesar, Giveon',
    album: 'Justice',
  },
  { name: 'Deja Vu', artists: 'Olivia Rodrigo', album: 'SOUR' },
  {
    name: 'Save Your Tears (Remix)',
    artists: 'The Weeknd, Ariana Grande',
    album: 'After Hours',
  },
  { name: 'Kiss Me More', artists: 'Doja Cat, SZA', album: 'Planet Her' },
  {
    name: 'Industry Baby',
    artists: 'Lil Nas X, Jack Harlow',
    album: 'Industry Baby',
  },
  { name: 'Blinding Lights', artists: 'The Weeknd', album: 'After Hours' },
  { name: 'Stay With Me', artists: 'Sam Smith', album: 'In the Lonely Hour' },
  { name: 'Shape of You', artists: 'Ed Sheeran', album: '÷' },
  {
    name: 'Uptown Funk',
    artists: 'Mark Ronson, Bruno Mars',
    album: 'Uptown Special',
  },
  { name: 'Rolling in the Deep', artists: 'Adele', album: '21' },
  { name: 'Thinking Out Loud', artists: 'Ed Sheeran', album: 'x' },
  { name: 'All of Me', artists: 'John Legend', album: 'Love in the Future' },
  { name: 'Radioactive', artists: 'Imagine Dragons', album: 'Night Visions' },
  { name: 'Happier', artists: 'Ed Sheeran', album: '÷' },
  { name: 'Havana', artists: 'Camila Cabello', album: 'Camila' },
  { name: 'Despacito', artists: 'Luis Fonsi, Daddy Yankee', album: 'Vida' },
  { name: 'Wrecking Ball', artists: 'Miley Cyrus', album: 'Bangerz' },
  {
    name: 'Bad Guy',
    artists: 'Billie Eilish',
    album: 'When We All Fall Asleep, Where Do We Go?',
  },
  { name: 'Watermelon Sugar', artists: 'Harry Styles', album: 'Fine Line' },
  { name: 'Circles', artists: 'Post Malone', album: "Hollywood's Bleeding" },
  {
    name: 'Shape of My Heart',
    artists: 'Sting',
    album: "Ten Summoner's Tales",
  },
];
